//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siswa
    {
        public int Id { get; set; }
        public string Nama { get; set; }
        public Nullable<int> Umur { get; set; }
        public string Alamat { get; set; }
        public Nullable<int> JurusanID { get; set; }
    
        public virtual Jurusan Jurusan { get; set; }
    }
}
